---
- name: Change Router Configuration
  hosts: CSR1kv2
  gather_facts: false
  connection: local

  tasks:
    - name: Change hostname
      ios_command:
        commands:
          - configure terminal
          - hostname CSRouter47
          - exit
